language: elm
node_js: node     # use "latest" version of Node.js

elm: 
  - elm0.19.0

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
