language: elm
node_js: node # use "latest" version of Node.js

elm:
  - latest-0.19.1

elm_test: 0.19.1

elm_format: 0.8.2

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
